#%RAML 1.0
title: Compress Decompress Example API
description: Compress Decompress Example API


/enqueue:
  post:
    responses:
      202:
        body:
          application/json:
          
/enqueueFile:
  post:
    responses:
      202:
        body:
          application/json:
 
/healthcheck:
  get:
    responses:
      200:
        body:
          application/json: